openapi: 3.0.0
info:
  title: "ATP DB"
  description: "An API ATP Player Data"
  version: "1.0.0"
servers:
  - url: "/api"
components:
  schemas:
    Player:
      type: "object"
      required:
        - fname
        - lname
        - country
      properties:
        fname:
          type: "string"
        lname:
          type: "string"
        born:
          type: "string"
        country:
          type: "string"
        birthplace:
          type: "string"
        dominant_hand:
          type: "string"
        backhand:
          type: "integer"
          enum: [1, 2]
        timestamp:
          type: "string"
  parameters:
    lname:
      name: "lname"
      description: "Last name of the player to get"
      in: path
      required: True
      schema:
        type: "string"
paths:
  /players:
    get:
      operationId: "players.read_all"
      tags:
        - Players
      summary: "Read the list of players"
      responses:
        "200":
          description: "Successfully read players list"
    post:
      operationId: "players.add"
      tags:
        - Players
      summary: "Add a player"
      requestBody:
        description: "Player to add"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "player"
              $ref: "#/components/schemas/Player"
      responses:
        "201":
          description: "Successfully added player"
  /players/{lname}:
    get:
      operationId: "players.read_one"
      tags:
        - Players
      summary: "Read one player"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "200":
          description: "Successfully read player"
    put:
      operationId: "players.update_one"
      tags:
        - Players
      summary: "Update one player"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "200":
          description: "Successfully updated player"
      requestBody:
        description: "Player to update"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "player_update"
              $ref: "#/components/schemas/Player"
